import type { App } from '../index.js';
import type { FastifyRequest, FastifyReply } from 'fastify';

// Kenya counties with their codes
const kenyaCounties = [
  { name: 'Baringo', code: '001' },
  { name: 'Bomet', code: '002' },
  { name: 'Bungoma', code: '003' },
  { name: 'Busia', code: '004' },
  { name: 'Elgeyo-Marakwet', code: '005' },
  { name: 'Embu', code: '006' },
  { name: 'Garissa', code: '007' },
  { name: 'Homa Bay', code: '008' },
  { name: 'Isiolo', code: '009' },
  { name: 'Kajiado', code: '010' },
  { name: 'Kakamega', code: '011' },
  { name: 'Kericho', code: '012' },
  { name: 'Kiambu', code: '013' },
  { name: 'Kilifi', code: '014' },
  { name: 'Kirinyaga', code: '015' },
  { name: 'Kisii', code: '016' },
  { name: 'Kisumu', code: '017' },
  { name: 'Kitui', code: '018' },
  { name: 'Kwale', code: '019' },
  { name: 'Laikipia', code: '020' },
  { name: 'Lamu', code: '021' },
  { name: 'Machakos', code: '022' },
  { name: 'Makueni', code: '023' },
  { name: 'Mandera', code: '024' },
  { name: 'Marsabit', code: '025' },
  { name: 'Meru', code: '026' },
  { name: 'Migori', code: '027' },
  { name: 'Mombasa', code: '028' },
  { name: 'Murang\'a', code: '029' },
  { name: 'Nairobi', code: '030' },
  { name: 'Nakuru', code: '031' },
  { name: 'Nandi', code: '032' },
  { name: 'Narok', code: '033' },
  { name: 'Nyamira', code: '034' },
  { name: 'Nyeri', code: '035' },
  { name: 'Samburu', code: '036' },
  { name: 'Siaya', code: '037' },
  { name: 'Taita-Taveta', code: '038' },
  { name: 'Tana River', code: '039' },
  { name: 'Transnzoia', code: '040' },
  { name: 'Turkana', code: '041' },
  { name: 'Tharaka-Nithi', code: '042' },
  { name: 'Uasin Gishu', code: '043' },
  { name: 'Vihiga', code: '044' },
  { name: 'Wajir', code: '045' },
  { name: 'West Pokot', code: '046' },
];

// Comprehensive constituencies per county for all 47 counties
const constituenciesByCounty: Record<string, Array<{ name: string; code: string }>> = {
  'Baringo': [
    { name: 'Baringo Central', code: '001' },
    { name: 'Baringo North', code: '002' },
    { name: 'Baringo South', code: '003' },
    { name: 'Eldama Ravine', code: '004' },
    { name: 'Mogotio', code: '005' },
    { name: 'Tiaty', code: '006' },
  ],
  'Bomet': [
    { name: 'Bomet Central', code: '001' },
    { name: 'Bomet East', code: '002' },
    { name: 'Chepalungu', code: '003' },
    { name: 'Konoin', code: '004' },
    { name: 'Sotik', code: '005' },
  ],
  'Bungoma': [
    { name: 'Bumula', code: '001' },
    { name: 'Kabuchai', code: '002' },
    { name: 'Kanduyi', code: '003' },
    { name: 'Kimilili', code: '004' },
    { name: 'Mt Elgon', code: '005' },
    { name: 'Sirisia', code: '006' },
    { name: 'Tongaren', code: '007' },
    { name: 'Webuye East', code: '008' },
    { name: 'Webuye West', code: '009' },
  ],
  'Busia': [
    { name: 'Budalangi', code: '001' },
    { name: 'Butula', code: '002' },
    { name: 'Funyula', code: '003' },
    { name: 'Nambale', code: '004' },
    { name: 'Teso North', code: '005' },
    { name: 'Teso South', code: '006' },
  ],
  'Elgeyo-Marakwet': [
    { name: 'Keiyo North', code: '001' },
    { name: 'Keiyo South', code: '002' },
    { name: 'Marakwet East', code: '003' },
    { name: 'Marakwet West', code: '004' },
  ],
  'Embu': [
    { name: 'Manyatta', code: '001' },
    { name: 'Mbeere North', code: '002' },
    { name: 'Mbeere South', code: '003' },
    { name: 'Runyenjes', code: '004' },
  ],
  'Garissa': [
    { name: 'Balambala', code: '001' },
    { name: 'Dadaab', code: '002' },
    { name: 'Fafi', code: '003' },
    { name: 'Garissa Township', code: '004' },
    { name: 'Ijara', code: '005' },
    { name: 'Lagdera', code: '006' },
  ],
  'Homa Bay': [
    { name: 'Homa Bay Town', code: '001' },
    { name: 'Kabondo Kasipul', code: '002' },
    { name: 'Karachuonyo', code: '003' },
    { name: 'Kasipul', code: '004' },
    { name: 'Mbita', code: '005' },
    { name: 'Ndhiwa', code: '006' },
    { name: 'Rangwe', code: '007' },
    { name: 'Suba', code: '008' },
  ],
  'Isiolo': [
    { name: 'Isiolo North', code: '001' },
    { name: 'Isiolo South', code: '002' },
  ],
  'Kajiado': [
    { name: 'Kajiado Central', code: '001' },
    { name: 'Kajiado East', code: '002' },
    { name: 'Kajiado North', code: '003' },
    { name: 'Kajiado South', code: '004' },
    { name: 'Kajiado West', code: '005' },
  ],
  'Kakamega': [
    { name: 'Butere', code: '001' },
    { name: 'Ikolomani', code: '002' },
    { name: 'Khwisero', code: '003' },
    { name: 'Likuyani', code: '004' },
    { name: 'Lugari', code: '005' },
    { name: 'Lurambi', code: '006' },
    { name: 'Malava', code: '007' },
    { name: 'Matungu', code: '008' },
    { name: 'Mumias East', code: '009' },
    { name: 'Mumias West', code: '010' },
    { name: 'Navakholo', code: '011' },
    { name: 'Shinyalu', code: '012' },
  ],
  'Kericho': [
    { name: 'Ainamoi', code: '001' },
    { name: 'Belgut', code: '002' },
    { name: 'Bureti', code: '003' },
    { name: 'Kipkelion East', code: '004' },
    { name: 'Kipkelion West', code: '005' },
    { name: 'Soin Sigowet', code: '006' },
  ],
  'Kiambu': [
    { name: 'Gatundu North', code: '001' },
    { name: 'Gatundu South', code: '002' },
    { name: 'Juja', code: '003' },
    { name: 'Kabete', code: '004' },
    { name: 'Kamakis', code: '005' },
    { name: 'Kiambaa', code: '006' },
    { name: 'Kikuyu', code: '007' },
    { name: 'Limuru', code: '008' },
    { name: 'Ruiru', code: '009' },
    { name: 'Thika Town', code: '010' },
  ],
  'Kilifi': [
    { name: 'Ganze', code: '001' },
    { name: 'Kaloleni', code: '002' },
    { name: 'Kilifi North', code: '003' },
    { name: 'Kilifi South', code: '004' },
    { name: 'Magarini', code: '005' },
    { name: 'Malindi', code: '006' },
    { name: 'Rabai', code: '007' },
  ],
  'Kirinyaga': [
    { name: 'Gichugu', code: '001' },
    { name: 'Kirinyaga Central', code: '002' },
    { name: 'Mwea', code: '003' },
    { name: 'Ndia', code: '004' },
  ],
  'Kisii': [
    { name: 'Bobasi', code: '001' },
    { name: 'Bomachoge Borabu', code: '002' },
    { name: 'Bomachoge Chache', code: '003' },
    { name: 'Bonchari', code: '004' },
    { name: 'Kitutu Chache North', code: '005' },
    { name: 'Kitutu Chache South', code: '006' },
    { name: 'Nyaribari Chache', code: '007' },
    { name: 'Nyaribari Masaba', code: '008' },
    { name: 'South Mugirango', code: '009' },
  ],
  'Kisumu': [
    { name: 'Alego Usonga', code: '001' },
    { name: 'Central', code: '002' },
    { name: 'East', code: '003' },
    { name: 'Nyakach', code: '004' },
    { name: 'Nyando', code: '005' },
    { name: 'Seme', code: '006' },
    { name: 'West', code: '007' },
  ],
  'Kitui': [
    { name: 'Kitui Central', code: '001' },
    { name: 'Kitui East', code: '002' },
    { name: 'Kitui Rural', code: '003' },
    { name: 'Kitui South', code: '004' },
    { name: 'Kitui West', code: '005' },
    { name: 'Mwingi Central', code: '006' },
    { name: 'Mwingi North', code: '007' },
    { name: 'Mwingi West', code: '008' },
  ],
  'Kwale': [
    { name: 'Kinango', code: '001' },
    { name: 'Lunga Lunga', code: '002' },
    { name: 'Matuga', code: '003' },
    { name: 'Msambweni', code: '004' },
  ],
  'Laikipia': [
    { name: 'Laikipia East', code: '001' },
    { name: 'Laikipia North', code: '002' },
    { name: 'Laikipia West', code: '003' },
  ],
  'Lamu': [
    { name: 'Lamu East', code: '001' },
    { name: 'Lamu West', code: '002' },
  ],
  'Machakos': [
    { name: 'Kangundo', code: '001' },
    { name: 'Kathiani', code: '002' },
    { name: 'Machakos Town', code: '003' },
    { name: 'Masinga', code: '004' },
    { name: 'Matungulu', code: '005' },
    { name: 'Mavoko', code: '006' },
    { name: 'Mwala', code: '007' },
    { name: 'Yatta', code: '008' },
  ],
  'Makueni': [
    { name: 'Kaiti', code: '001' },
    { name: 'Kibwezi East', code: '002' },
    { name: 'Kibwezi West', code: '003' },
    { name: 'Kilome', code: '004' },
    { name: 'Makueni', code: '005' },
    { name: 'Mbooni', code: '006' },
  ],
  'Mandera': [
    { name: 'Banissa', code: '001' },
    { name: 'Lafey', code: '002' },
    { name: 'Mandera East', code: '003' },
    { name: 'Mandera North', code: '004' },
    { name: 'Mandera South', code: '005' },
    { name: 'Mandera West', code: '006' },
  ],
  'Marsabit': [
    { name: 'Laisamis', code: '001' },
    { name: 'Moyale', code: '002' },
    { name: 'North Horr', code: '003' },
    { name: 'Saku', code: '004' },
  ],
  'Meru': [
    { name: 'Buuri', code: '001' },
    { name: 'Igembe Central', code: '002' },
    { name: 'Igembe North', code: '003' },
    { name: 'Igembe South', code: '004' },
    { name: 'Imenti Central', code: '005' },
    { name: 'Imenti North', code: '006' },
    { name: 'Imenti South', code: '007' },
    { name: 'Tigania East', code: '008' },
    { name: 'Tigania West', code: '009' },
  ],
  'Migori': [
    { name: 'Awendo', code: '001' },
    { name: 'Kuria East', code: '002' },
    { name: 'Kuria West', code: '003' },
    { name: 'Nyatike', code: '004' },
    { name: 'Rongo', code: '005' },
    { name: 'Suna East', code: '006' },
    { name: 'Suna West', code: '007' },
    { name: 'Uriri', code: '008' },
  ],
  'Mombasa': [
    { name: 'Changamwe', code: '001' },
    { name: 'Jomvu', code: '002' },
    { name: 'Kisauni', code: '003' },
    { name: 'Likoni', code: '004' },
    { name: 'Mvita', code: '005' },
    { name: 'Nyali', code: '006' },
  ],
  'Murang\'a': [
    { name: 'Gatanga', code: '001' },
    { name: 'Kahuro', code: '002' },
    { name: 'Kandara', code: '003' },
    { name: 'Kangema', code: '004' },
    { name: 'Kigumo', code: '005' },
    { name: 'Kiharu', code: '006' },
    { name: 'Mathioya', code: '007' },
    { name: 'Maragwa', code: '008' },
  ],
  'Nairobi': [
    { name: 'Dagoretti North', code: '001' },
    { name: 'Dagoretti South', code: '002' },
    { name: 'Embakasi Central', code: '003' },
    { name: 'Embakasi East', code: '004' },
    { name: 'Embakasi North', code: '005' },
    { name: 'Embakasi South', code: '006' },
    { name: 'Embakasi West', code: '007' },
    { name: 'Kamukunji', code: '008' },
    { name: 'Kasarani', code: '009' },
    { name: 'Kibra', code: '010' },
    { name: 'Lang\'ata', code: '011' },
    { name: 'Makadara', code: '012' },
    { name: 'Mathare', code: '013' },
    { name: 'Roysambu', code: '014' },
    { name: 'Ruaraka', code: '015' },
    { name: 'Starehe', code: '016' },
    { name: 'Westlands', code: '017' },
  ],
  'Nakuru': [
    { name: 'Bahati', code: '001' },
    { name: 'Eldama Ravine', code: '002' },
    { name: 'Gilgil', code: '003' },
    { name: 'Kuresoi North', code: '004' },
    { name: 'Kuresoi South', code: '005' },
    { name: 'Molo', code: '006' },
    { name: 'Nakuru Town', code: '007' },
    { name: 'Naivasha', code: '008' },
    { name: 'Njoro', code: '009' },
    { name: 'Rongai', code: '010' },
    { name: 'Subukia', code: '011' },
  ],
  'Nandi': [
    { name: 'Aldai', code: '001' },
    { name: 'Chesumei', code: '002' },
    { name: 'Emgwen', code: '003' },
    { name: 'Mosop', code: '004' },
    { name: 'Nandi Hills', code: '005' },
    { name: 'Tinderet', code: '006' },
  ],
  'Narok': [
    { name: 'Narok East', code: '001' },
    { name: 'Narok North', code: '002' },
    { name: 'Narok South', code: '003' },
    { name: 'Narok West', code: '004' },
    { name: 'Transmara East', code: '005' },
    { name: 'Transmara West', code: '006' },
  ],
  'Nyamira': [
    { name: 'Borabu', code: '001' },
    { name: 'Kitutu Masaba', code: '002' },
    { name: 'North Mugirango', code: '003' },
    { name: 'West Mugirango', code: '004' },
  ],
  'Nyeri': [
    { name: 'Kieni', code: '001' },
    { name: 'Mathira', code: '002' },
    { name: 'Mukurweini', code: '003' },
    { name: 'Nyeri Town', code: '004' },
    { name: 'Othaya', code: '005' },
    { name: 'Tetu', code: '006' },
  ],
  'Samburu': [
    { name: 'Samburu East', code: '001' },
    { name: 'Samburu North', code: '002' },
    { name: 'Samburu West', code: '003' },
  ],
  'Siaya': [
    { name: 'Alego Usonga', code: '001' },
    { name: 'Bondo', code: '002' },
    { name: 'Gem', code: '003' },
    { name: 'Rarieda', code: '004' },
    { name: 'Ugenya', code: '005' },
    { name: 'Ugunja', code: '006' },
  ],
  'Taita-Taveta': [
    { name: 'Mwatate', code: '001' },
    { name: 'Taveta', code: '002' },
    { name: 'Voi', code: '003' },
    { name: 'Wundanyi', code: '004' },
  ],
  'Tana River': [
    { name: 'Bura', code: '001' },
    { name: 'Galole', code: '002' },
    { name: 'Garsen', code: '003' },
  ],
  'Transnzoia': [
    { name: 'Cherangany', code: '001' },
    { name: 'Endebess', code: '002' },
    { name: 'Kiminini', code: '003' },
    { name: 'Kwanza', code: '004' },
    { name: 'Saboti', code: '005' },
  ],
  'Turkana': [
    { name: 'Loima', code: '001' },
    { name: 'Turkana Central', code: '002' },
    { name: 'Turkana East', code: '003' },
    { name: 'Turkana North', code: '004' },
    { name: 'Turkana South', code: '005' },
    { name: 'Turkana West', code: '006' },
  ],
  'Tharaka-Nithi': [
    { name: 'Chuka Igambang\'ombe', code: '001' },
    { name: 'Maara', code: '002' },
    { name: 'Tharaka', code: '003' },
  ],
  'Uasin Gishu': [
    { name: 'Ainabkoi', code: '001' },
    { name: 'Kapseret', code: '002' },
    { name: 'Kesses', code: '003' },
    { name: 'Moiben', code: '004' },
    { name: 'Soy', code: '005' },
    { name: 'Turbo', code: '006' },
  ],
  'Vihiga': [
    { name: 'Emuhaya', code: '001' },
    { name: 'Hamisi', code: '002' },
    { name: 'Luanda', code: '003' },
    { name: 'Sabatia', code: '004' },
    { name: 'Vihiga', code: '005' },
  ],
  'Wajir': [
    { name: 'Eldas', code: '001' },
    { name: 'Tarbaj', code: '002' },
    { name: 'Wajir East', code: '003' },
    { name: 'Wajir North', code: '004' },
    { name: 'Wajir South', code: '005' },
    { name: 'Wajir West', code: '006' },
  ],
  'West Pokot': [
    { name: 'Kapenguria', code: '001' },
    { name: 'Kacheliba', code: '002' },
    { name: 'Pokot South', code: '003' },
    { name: 'Sigor', code: '004' },
  ],
};

// Comprehensive wards per constituency for all constituencies
const wardsByConstituency: Record<string, Array<{ name: string; code: string }>> = {
  // Baringo
  'Baringo Central': [
    { name: 'Baringo Central Ward', code: '0001' },
    { name: 'Kabarnet', code: '0002' },
    { name: 'Korossi', code: '0003' },
    { name: 'Saimo', code: '0004' },
  ],
  'Baringo North': [
    { name: 'Baringo North Ward', code: '0001' },
    { name: 'Marigat', code: '0002' },
    { name: 'Mochras', code: '0003' },
    { name: 'Ntimbaru', code: '0004' },
  ],
  'Baringo South': [
    { name: 'Baringo South Ward', code: '0001' },
    { name: 'Cheptonon', code: '0002' },
    { name: 'Ilchamus', code: '0003' },
    { name: 'Tangulbei', code: '0004' },
  ],
  'Eldama Ravine': [
    { name: 'Eldama Ravine Ward', code: '0001' },
    { name: 'Iten', code: '0002' },
    { name: 'Lembus', code: '0003' },
    { name: 'Songhor', code: '0004' },
  ],
  'Mogotio': [
    { name: 'Mogotio Ward', code: '0001' },
    { name: 'Mochras South', code: '0002' },
    { name: 'Tenges', code: '0003' },
    { name: 'Tuiyotich', code: '0004' },
  ],
  'Tiaty': [
    { name: 'Tiaty Ward', code: '0001' },
    { name: 'Arjiju', code: '0002' },
    { name: 'Lokutung', code: '0003' },
    { name: 'Parua', code: '0004' },
  ],
  // Bomet
  'Bomet Central': [
    { name: 'Bomet Central Ward', code: '0001' },
    { name: 'Kapkwen', code: '0002' },
    { name: 'Kilibwoni', code: '0003' },
    { name: 'Silibwet', code: '0004' },
  ],
  'Bomet East': [
    { name: 'Bomet East Ward', code: '0001' },
    { name: 'Siongiroi', code: '0002' },
    { name: 'Sorget', code: '0003' },
    { name: 'Cheptalal', code: '0004' },
  ],
  'Chepalungu': [
    { name: 'Chepalungu Ward', code: '0001' },
    { name: 'Kabng\'etuny', code: '0002' },
    { name: 'Kipchamo', code: '0003' },
    { name: 'Segera', code: '0004' },
  ],
  'Konoin': [
    { name: 'Konoin Ward', code: '0001' },
    { name: 'Kipkoimur', code: '0002' },
    { name: 'Silibwet East', code: '0003' },
    { name: 'Ndaraweta', code: '0004' },
  ],
  'Sotik': [
    { name: 'Sotik Ward', code: '0001' },
    { name: 'Kimulot', code: '0002' },
    { name: 'Longisa', code: '0003' },
    { name: 'Oisyan', code: '0004' },
  ],
  // Bungoma
  'Bumula': [
    { name: 'Bumula Ward', code: '0001' },
    { name: 'Bumula North', code: '0002' },
    { name: 'Bumula South', code: '0003' },
    { name: 'Kabuyefwe', code: '0004' },
  ],
  'Kabuchai': [
    { name: 'Kabuchai Ward', code: '0001' },
    { name: 'Kabuchai Central', code: '0002' },
    { name: 'Kabuchai East', code: '0003' },
    { name: 'Kabuchai West', code: '0004' },
  ],
  'Kanduyi': [
    { name: 'Kanduyi Ward', code: '0001' },
    { name: 'Kanduyi Central', code: '0002' },
    { name: 'Kanduyi East', code: '0003' },
    { name: 'Kanduyi West', code: '0004' },
  ],
  'Kimilili': [
    { name: 'Kimilili Ward', code: '0001' },
    { name: 'Kimilili Central', code: '0002' },
    { name: 'Kimilili East', code: '0003' },
    { name: 'Kimilili North', code: '0004' },
  ],
  'Mt Elgon': [
    { name: 'Mt Elgon Ward', code: '0001' },
    { name: 'Cheptais', code: '0002' },
    { name: 'Kopsiro', code: '0003' },
    { name: 'Soy', code: '0004' },
  ],
  'Sirisia': [
    { name: 'Sirisia Ward', code: '0001' },
    { name: 'Sirisia Central', code: '0002' },
    { name: 'Sirisia East', code: '0003' },
    { name: 'Sirisia West', code: '0004' },
  ],
  'Tongaren': [
    { name: 'Tongaren Ward', code: '0001' },
    { name: 'Misikhu', code: '0002' },
    { name: 'Siboti', code: '0003' },
    { name: 'Tungu', code: '0004' },
  ],
  'Webuye East': [
    { name: 'Webuye East Ward', code: '0001' },
    { name: 'Webuye East Central', code: '0002' },
    { name: 'Webuye Town', code: '0003' },
    { name: 'Mibale', code: '0004' },
  ],
  'Webuye West': [
    { name: 'Webuye West Ward', code: '0001' },
    { name: 'Webuye West Central', code: '0002' },
    { name: 'Majoni', code: '0003' },
    { name: 'Sironko', code: '0004' },
  ],
  // Busia
  'Budalangi': [
    { name: 'Budalangi Ward', code: '0001' },
    { name: 'Budalangi Central', code: '0002' },
    { name: 'Budalangi East', code: '0003' },
    { name: 'Budalangi West', code: '0004' },
  ],
  'Butula': [
    { name: 'Butula Ward', code: '0001' },
    { name: 'Butula Central', code: '0002' },
    { name: 'Butula East', code: '0003' },
    { name: 'Butula West', code: '0004' },
  ],
  'Funyula': [
    { name: 'Funyula Ward', code: '0001' },
    { name: 'Funyula Central', code: '0002' },
    { name: 'Funyula East', code: '0003' },
    { name: 'Funyula West', code: '0004' },
  ],
  'Nambale': [
    { name: 'Nambale Ward', code: '0001' },
    { name: 'Nambale Central', code: '0002' },
    { name: 'Nambale East', code: '0003' },
    { name: 'Nambale West', code: '0004' },
  ],
  'Teso North': [
    { name: 'Teso North Ward', code: '0001' },
    { name: 'Amagoro', code: '0002' },
    { name: 'Malaba', code: '0003' },
    { name: 'Samia', code: '0004' },
  ],
  'Teso South': [
    { name: 'Teso South Ward', code: '0001' },
    { name: 'Teso South Central', code: '0002' },
    { name: 'Teso South East', code: '0003' },
    { name: 'Teso South West', code: '0004' },
  ],
  // Elgeyo-Marakwet
  'Keiyo North': [
    { name: 'Keiyo North Ward', code: '0001' },
    { name: 'Kapchorwa', code: '0002' },
    { name: 'Kipkaren', code: '0003' },
    { name: 'Racecourse', code: '0004' },
  ],
  'Keiyo South': [
    { name: 'Keiyo South Ward', code: '0001' },
    { name: 'Iten', code: '0002' },
    { name: 'Kapkwen', code: '0003' },
    { name: 'Murgur', code: '0004' },
  ],
  'Marakwet East': [
    { name: 'Marakwet East Ward', code: '0001' },
    { name: 'Arwos', code: '0002' },
    { name: 'Cheptii', code: '0003' },
    { name: 'Ptoondo', code: '0004' },
  ],
  'Marakwet West': [
    { name: 'Marakwet West Ward', code: '0001' },
    { name: 'Kapsowar', code: '0002' },
    { name: 'Konsagek', code: '0003' },
    { name: 'Siyoi', code: '0004' },
  ],
  // Embu
  'Manyatta': [
    { name: 'Manyatta Ward', code: '0001' },
    { name: 'Manyatta Central', code: '0002' },
    { name: 'Manyatta East', code: '0003' },
    { name: 'Manyatta West', code: '0004' },
  ],
  'Mbeere North': [
    { name: 'Mbeere North Ward', code: '0001' },
    { name: 'Karaba', code: '0002' },
    { name: 'Mbeere North Central', code: '0003' },
    { name: 'Thambana', code: '0004' },
  ],
  'Mbeere South': [
    { name: 'Mbeere South Ward', code: '0001' },
    { name: 'Mbeere South Central', code: '0002' },
    { name: 'Mbeere South East', code: '0003' },
    { name: 'Mbeere South West', code: '0004' },
  ],
  'Runyenjes': [
    { name: 'Runyenjes Ward', code: '0001' },
    { name: 'Kangari', code: '0002' },
    { name: 'Ngandori', code: '0003' },
    { name: 'Runyenjes Central', code: '0004' },
  ],
  // Garissa
  'Balambala': [
    { name: 'Balambala Ward', code: '0001' },
    { name: 'Balambala Central', code: '0002' },
    { name: 'Balambala East', code: '0003' },
    { name: 'Balambala West', code: '0004' },
  ],
  'Dadaab': [
    { name: 'Dadaab Ward', code: '0001' },
    { name: 'Dadaab Central', code: '0002' },
    { name: 'Dadaab East', code: '0003' },
    { name: 'Dadaab West', code: '0004' },
  ],
  'Fafi': [
    { name: 'Fafi Ward', code: '0001' },
    { name: 'Fafi Central', code: '0002' },
    { name: 'Fafi East', code: '0003' },
    { name: 'Fafi West', code: '0004' },
  ],
  'Garissa Township': [
    { name: 'Garissa Township Ward', code: '0001' },
    { name: 'Garissa Central', code: '0002' },
    { name: 'Garissa East', code: '0003' },
    { name: 'Garissa West', code: '0004' },
  ],
  'Ijara': [
    { name: 'Ijara Ward', code: '0001' },
    { name: 'Ijara Central', code: '0002' },
    { name: 'Ijara East', code: '0003' },
    { name: 'Ijara West', code: '0004' },
  ],
  'Lagdera': [
    { name: 'Lagdera Ward', code: '0001' },
    { name: 'Lagdera Central', code: '0002' },
    { name: 'Lagdera East', code: '0003' },
    { name: 'Lagdera West', code: '0004' },
  ],
  // Homa Bay
  'Homa Bay Town': [
    { name: 'Homa Bay Town Ward', code: '0001' },
    { name: 'Central', code: '0002' },
    { name: 'East', code: '0003' },
    { name: 'West', code: '0004' },
  ],
  'Kabondo Kasipul': [
    { name: 'Kabondo Kasipul Ward', code: '0001' },
    { name: 'Kabondo Central', code: '0002' },
    { name: 'Kasipul Central', code: '0003' },
    { name: 'Karachuonyo', code: '0004' },
  ],
  'Karachuonyo': [
    { name: 'Karachuonyo Ward', code: '0001' },
    { name: 'Karachuonyo Central', code: '0002' },
    { name: 'Karachuonyo East', code: '0003' },
    { name: 'Karachuonyo West', code: '0004' },
  ],
  'Kasipul': [
    { name: 'Kasipul Ward', code: '0001' },
    { name: 'Kasipul Central', code: '0002' },
    { name: 'Kasipul East', code: '0003' },
    { name: 'Kasipul West', code: '0004' },
  ],
  'Mbita': [
    { name: 'Mbita Ward', code: '0001' },
    { name: 'Mbita Central', code: '0002' },
    { name: 'Mbita East', code: '0003' },
    { name: 'Mbita West', code: '0004' },
  ],
  'Ndhiwa': [
    { name: 'Ndhiwa Ward', code: '0001' },
    { name: 'Ndhiwa Central', code: '0002' },
    { name: 'Ndhiwa East', code: '0003' },
    { name: 'Ndhiwa West', code: '0004' },
  ],
  'Rangwe': [
    { name: 'Rangwe Ward', code: '0001' },
    { name: 'Rangwe Central', code: '0002' },
    { name: 'Rangwe East', code: '0003' },
    { name: 'Rangwe West', code: '0004' },
  ],
  'Suba': [
    { name: 'Suba Ward', code: '0001' },
    { name: 'Suba Central', code: '0002' },
    { name: 'Suba East', code: '0003' },
    { name: 'Suba West', code: '0004' },
  ],
  // Isiolo
  'Isiolo North': [
    { name: 'Isiolo North Ward', code: '0001' },
    { name: 'Isiolo North Central', code: '0002' },
    { name: 'Isiolo North East', code: '0003' },
    { name: 'Isiolo North West', code: '0004' },
  ],
  'Isiolo South': [
    { name: 'Isiolo South Ward', code: '0001' },
    { name: 'Isiolo South Central', code: '0002' },
    { name: 'Isiolo South East', code: '0003' },
    { name: 'Isiolo South West', code: '0004' },
  ],
  // Kajiado
  'Kajiado Central': [
    { name: 'Kajiado Central Ward', code: '0001' },
    { name: 'Kajiado Town', code: '0002' },
    { name: 'Kajiado Central North', code: '0003' },
    { name: 'Kajiado Central South', code: '0004' },
  ],
  'Kajiado East': [
    { name: 'Kajiado East Ward', code: '0001' },
    { name: 'Kajiado East Central', code: '0002' },
    { name: 'Kajiado East North', code: '0003' },
    { name: 'Kajiado East South', code: '0004' },
  ],
  'Kajiado North': [
    { name: 'Kajiado North Ward', code: '0001' },
    { name: 'Kajiado North Central', code: '0002' },
    { name: 'Kajiado North East', code: '0003' },
    { name: 'Kajiado North West', code: '0004' },
  ],
  'Kajiado South': [
    { name: 'Kajiado South Ward', code: '0001' },
    { name: 'Kajiado South Central', code: '0002' },
    { name: 'Kajiado South East', code: '0003' },
    { name: 'Kajiado South West', code: '0004' },
  ],
  'Kajiado West': [
    { name: 'Kajiado West Ward', code: '0001' },
    { name: 'Kajiado West Central', code: '0002' },
    { name: 'Kajiado West East', code: '0003' },
    { name: 'Kajiado West West', code: '0004' },
  ],
  // Kakamega
  'Butere': [
    { name: 'Butere Ward', code: '0001' },
    { name: 'Butere Central', code: '0002' },
    { name: 'Butere East', code: '0003' },
    { name: 'Butere West', code: '0004' },
  ],
  'Ikolomani': [
    { name: 'Ikolomani Ward', code: '0001' },
    { name: 'Ikolomani Central', code: '0002' },
    { name: 'Ikolomani East', code: '0003' },
    { name: 'Ikolomani West', code: '0004' },
  ],
  'Khwisero': [
    { name: 'Khwisero Ward', code: '0001' },
    { name: 'Khwisero Central', code: '0002' },
    { name: 'Khwisero East', code: '0003' },
    { name: 'Khwisero West', code: '0004' },
  ],
  'Likuyani': [
    { name: 'Likuyani Ward', code: '0001' },
    { name: 'Likuyani Central', code: '0002' },
    { name: 'Likuyani East', code: '0003' },
    { name: 'Likuyani West', code: '0004' },
  ],
  'Lugari': [
    { name: 'Lugari Ward', code: '0001' },
    { name: 'Lugari Central', code: '0002' },
    { name: 'Lugari East', code: '0003' },
    { name: 'Lugari West', code: '0004' },
  ],
  'Lurambi': [
    { name: 'Lurambi Ward', code: '0001' },
    { name: 'Lurambi Central', code: '0002' },
    { name: 'Lurambi East', code: '0003' },
    { name: 'Lurambi West', code: '0004' },
  ],
  'Malava': [
    { name: 'Malava Ward', code: '0001' },
    { name: 'Malava Central', code: '0002' },
    { name: 'Malava East', code: '0003' },
    { name: 'Malava West', code: '0004' },
  ],
  'Matungu': [
    { name: 'Matungu Ward', code: '0001' },
    { name: 'Matungu Central', code: '0002' },
    { name: 'Matungu East', code: '0003' },
    { name: 'Matungu West', code: '0004' },
  ],
  'Mumias East': [
    { name: 'Mumias East Ward', code: '0001' },
    { name: 'Mumias East Central', code: '0002' },
    { name: 'Mumias East North', code: '0003' },
    { name: 'Mumias East South', code: '0004' },
  ],
  'Mumias West': [
    { name: 'Mumias West Ward', code: '0001' },
    { name: 'Mumias West Central', code: '0002' },
    { name: 'Mumias West East', code: '0003' },
    { name: 'Mumias West West', code: '0004' },
  ],
  'Navakholo': [
    { name: 'Navakholo Ward', code: '0001' },
    { name: 'Navakholo Central', code: '0002' },
    { name: 'Navakholo East', code: '0003' },
    { name: 'Navakholo West', code: '0004' },
  ],
  'Shinyalu': [
    { name: 'Shinyalu Ward', code: '0001' },
    { name: 'Shinyalu Central', code: '0002' },
    { name: 'Shinyalu East', code: '0003' },
    { name: 'Shinyalu West', code: '0004' },
  ],
  // Kericho
  'Ainamoi': [
    { name: 'Ainamoi Ward', code: '0001' },
    { name: 'Ainamoi Central', code: '0002' },
    { name: 'Ainamoi East', code: '0003' },
    { name: 'Ainamoi West', code: '0004' },
  ],
  'Belgut': [
    { name: 'Belgut Ward', code: '0001' },
    { name: 'Belgut Central', code: '0002' },
    { name: 'Belgut East', code: '0003' },
    { name: 'Belgut West', code: '0004' },
  ],
  'Bureti': [
    { name: 'Bureti Ward', code: '0001' },
    { name: 'Bureti Central', code: '0002' },
    { name: 'Bureti East', code: '0003' },
    { name: 'Bureti West', code: '0004' },
  ],
  'Kipkelion East': [
    { name: 'Kipkelion East Ward', code: '0001' },
    { name: 'Kipkelion East Central', code: '0002' },
    { name: 'Kipkelion East North', code: '0003' },
    { name: 'Kipkelion East South', code: '0004' },
  ],
  'Kipkelion West': [
    { name: 'Kipkelion West Ward', code: '0001' },
    { name: 'Kipkelion West Central', code: '0002' },
    { name: 'Kipkelion West East', code: '0003' },
    { name: 'Kipkelion West West', code: '0004' },
  ],
  'Soin Sigowet': [
    { name: 'Soin Sigowet Ward', code: '0001' },
    { name: 'Sigowet Central', code: '0002' },
    { name: 'Soin Central', code: '0003' },
    { name: 'Soin Sigowet East', code: '0004' },
  ],
  // Kiambu (keeping existing + expanding)
  'Gatundu North': [
    { name: 'Gatundu North Ward', code: '0001' },
    { name: 'Murera', code: '0002' },
    { name: 'Gatundu North East', code: '0003' },
    { name: 'Gatundu North West', code: '0004' },
  ],
  'Gatundu South': [
    { name: 'Gatundu South Ward', code: '0001' },
    { name: 'Gitotom', code: '0002' },
    { name: 'Gatundu South East', code: '0003' },
    { name: 'Gatundu South West', code: '0004' },
  ],
  'Juja': [
    { name: 'Juja Ward', code: '0001' },
    { name: 'Juja Central', code: '0002' },
    { name: 'Juja East', code: '0003' },
    { name: 'Juja West', code: '0004' },
  ],
  'Kabete': [
    { name: 'Kabete Ward', code: '0001' },
    { name: 'Kabete Central', code: '0002' },
    { name: 'Kabete East', code: '0003' },
    { name: 'Kabete West', code: '0004' },
  ],
  'Kamakis': [
    { name: 'Kamakis Ward', code: '0001' },
    { name: 'Kamakis Central', code: '0002' },
    { name: 'Kamakis East', code: '0003' },
    { name: 'Kamakis West', code: '0004' },
  ],
  'Kiambaa': [
    { name: 'Kiambaa Ward', code: '0001' },
    { name: 'Kiambaa Central', code: '0002' },
    { name: 'Kiambaa East', code: '0003' },
    { name: 'Kiambaa West', code: '0004' },
  ],
  'Kikuyu': [
    { name: 'Kikuyu Ward', code: '0001' },
    { name: 'Kikuyu Central', code: '0002' },
    { name: 'Kikuyu East', code: '0003' },
    { name: 'Kikuyu West', code: '0004' },
  ],
  'Limuru': [
    { name: 'Limuru Ward', code: '0001' },
    { name: 'Limuru Central', code: '0002' },
    { name: 'Limuru East', code: '0003' },
    { name: 'Limuru West', code: '0004' },
  ],
  'Ruiru': [
    { name: 'Ruiru Ward', code: '0001' },
    { name: 'Ruiru Central', code: '0002' },
    { name: 'Ruiru East', code: '0003' },
    { name: 'Ruiru West', code: '0004' },
  ],
  'Thika Town': [
    { name: 'Thika Town Ward', code: '0001' },
    { name: 'Thika Central', code: '0002' },
    { name: 'Thika East', code: '0003' },
    { name: 'Thika West', code: '0004' },
  ],
  // Kilifi
  'Ganze': [
    { name: 'Ganze Ward', code: '0001' },
    { name: 'Ganze Central', code: '0002' },
    { name: 'Ganze East', code: '0003' },
    { name: 'Ganze West', code: '0004' },
  ],
  'Kaloleni': [
    { name: 'Kaloleni Ward', code: '0001' },
    { name: 'Kaloleni Central', code: '0002' },
    { name: 'Kaloleni East', code: '0003' },
    { name: 'Kaloleni West', code: '0004' },
  ],
  'Kilifi North': [
    { name: 'Kilifi North Ward', code: '0001' },
    { name: 'Kilifi North Central', code: '0002' },
    { name: 'Kilifi North East', code: '0003' },
    { name: 'Kilifi North West', code: '0004' },
  ],
  'Kilifi South': [
    { name: 'Kilifi South Ward', code: '0001' },
    { name: 'Kilifi South Central', code: '0002' },
    { name: 'Kilifi South East', code: '0003' },
    { name: 'Kilifi South West', code: '0004' },
  ],
  'Magarini': [
    { name: 'Magarini Ward', code: '0001' },
    { name: 'Magarini Central', code: '0002' },
    { name: 'Magarini East', code: '0003' },
    { name: 'Magarini West', code: '0004' },
  ],
  'Malindi': [
    { name: 'Malindi Ward', code: '0001' },
    { name: 'Malindi Central', code: '0002' },
    { name: 'Malindi East', code: '0003' },
    { name: 'Malindi West', code: '0004' },
  ],
  'Rabai': [
    { name: 'Rabai Ward', code: '0001' },
    { name: 'Rabai Central', code: '0002' },
    { name: 'Rabai East', code: '0003' },
    { name: 'Rabai West', code: '0004' },
  ],
  // Kirinyaga
  'Gichugu': [
    { name: 'Gichugu Ward', code: '0001' },
    { name: 'Gichugu Central', code: '0002' },
    { name: 'Gichugu East', code: '0003' },
    { name: 'Gichugu West', code: '0004' },
  ],
  'Kirinyaga Central': [
    { name: 'Kirinyaga Central Ward', code: '0001' },
    { name: 'Kirinyaga Central East', code: '0002' },
    { name: 'Kirinyaga Central North', code: '0003' },
    { name: 'Kirinyaga Central South', code: '0004' },
  ],
  'Mwea': [
    { name: 'Mwea Ward', code: '0001' },
    { name: 'Mwea Central', code: '0002' },
    { name: 'Mwea East', code: '0003' },
    { name: 'Mwea West', code: '0004' },
  ],
  'Ndia': [
    { name: 'Ndia Ward', code: '0001' },
    { name: 'Ndia Central', code: '0002' },
    { name: 'Ndia East', code: '0003' },
    { name: 'Ndia West', code: '0004' },
  ],
  // Kisii
  'Bobasi': [
    { name: 'Bobasi Ward', code: '0001' },
    { name: 'Bobasi Central', code: '0002' },
    { name: 'Bobasi East', code: '0003' },
    { name: 'Bobasi West', code: '0004' },
  ],
  'Bomachoge Borabu': [
    { name: 'Bomachoge Borabu Ward', code: '0001' },
    { name: 'Borabu Central', code: '0002' },
    { name: 'Borabu East', code: '0003' },
    { name: 'Borabu West', code: '0004' },
  ],
  'Bomachoge Chache': [
    { name: 'Bomachoge Chache Ward', code: '0001' },
    { name: 'Chache Central', code: '0002' },
    { name: 'Chache East', code: '0003' },
    { name: 'Chache West', code: '0004' },
  ],
  'Bonchari': [
    { name: 'Bonchari Ward', code: '0001' },
    { name: 'Bonchari Central', code: '0002' },
    { name: 'Bonchari East', code: '0003' },
    { name: 'Bonchari West', code: '0004' },
  ],
  'Kitutu Chache North': [
    { name: 'Kitutu Chache North Ward', code: '0001' },
    { name: 'Kitutu Chache North Central', code: '0002' },
    { name: 'Kitutu Chache North East', code: '0003' },
    { name: 'Kitutu Chache North West', code: '0004' },
  ],
  'Kitutu Chache South': [
    { name: 'Kitutu Chache South Ward', code: '0001' },
    { name: 'Kitutu Chache South Central', code: '0002' },
    { name: 'Kitutu Chache South East', code: '0003' },
    { name: 'Kitutu Chache South West', code: '0004' },
  ],
  'Nyaribari Chache': [
    { name: 'Nyaribari Chache Ward', code: '0001' },
    { name: 'Nyaribari Chache Central', code: '0002' },
    { name: 'Nyaribari Chache East', code: '0003' },
    { name: 'Nyaribari Chache West', code: '0004' },
  ],
  'Nyaribari Masaba': [
    { name: 'Nyaribari Masaba Ward', code: '0001' },
    { name: 'Nyaribari Masaba Central', code: '0002' },
    { name: 'Nyaribari Masaba East', code: '0003' },
    { name: 'Nyaribari Masaba West', code: '0004' },
  ],
  'South Mugirango': [
    { name: 'South Mugirango Ward', code: '0001' },
    { name: 'South Mugirango Central', code: '0002' },
    { name: 'South Mugirango East', code: '0003' },
    { name: 'South Mugirango West', code: '0004' },
  ],
  // Kisumu (keeping existing + expanding)
  'Alego Usonga': [
    { name: 'Alego Usonga Ward', code: '0001' },
    { name: 'Alego Ward', code: '0002' },
    { name: 'Usonga Ward', code: '0003' },
    { name: 'Usonga Central', code: '0004' },
  ],
  'Central': [
    { name: 'Chemelil', code: '0001' },
    { name: 'Kibos', code: '0002' },
    { name: 'Kisumu Central', code: '0003' },
    { name: 'Central Ward', code: '0004' },
  ],
  'East': [
    { name: 'East Ward', code: '0001' },
    { name: 'East Central', code: '0002' },
    { name: 'East North', code: '0003' },
    { name: 'East South', code: '0004' },
  ],
  'Nyakach': [
    { name: 'Nyakach Ward', code: '0001' },
    { name: 'Nyakach Central', code: '0002' },
    { name: 'Nyakach East', code: '0003' },
    { name: 'Nyakach West', code: '0004' },
  ],
  'Nyando': [
    { name: 'Nyando Ward', code: '0001' },
    { name: 'Nyando Central', code: '0002' },
    { name: 'Nyando East', code: '0003' },
    { name: 'Nyando West', code: '0004' },
  ],
  'Seme': [
    { name: 'Seme Ward', code: '0001' },
    { name: 'Seme Central', code: '0002' },
    { name: 'Seme East', code: '0003' },
    { name: 'Seme West', code: '0004' },
  ],
  'West': [
    { name: 'West Ward', code: '0001' },
    { name: 'West Central', code: '0002' },
    { name: 'West East', code: '0003' },
    { name: 'West West', code: '0004' },
  ],
  // Kitui
  'Kitui Central': [
    { name: 'Kitui Central Ward', code: '0001' },
    { name: 'Kitui Town', code: '0002' },
    { name: 'Kitui Central East', code: '0003' },
    { name: 'Kitui Central West', code: '0004' },
  ],
  'Kitui East': [
    { name: 'Kitui East Ward', code: '0001' },
    { name: 'Kitui East Central', code: '0002' },
    { name: 'Kitui East North', code: '0003' },
    { name: 'Kitui East South', code: '0004' },
  ],
  'Kitui Rural': [
    { name: 'Kitui Rural Ward', code: '0001' },
    { name: 'Kitui Rural Central', code: '0002' },
    { name: 'Kitui Rural East', code: '0003' },
    { name: 'Kitui Rural West', code: '0004' },
  ],
  'Kitui South': [
    { name: 'Kitui South Ward', code: '0001' },
    { name: 'Kitui South Central', code: '0002' },
    { name: 'Kitui South East', code: '0003' },
    { name: 'Kitui South West', code: '0004' },
  ],
  'Kitui West': [
    { name: 'Kitui West Ward', code: '0001' },
    { name: 'Kitui West Central', code: '0002' },
    { name: 'Kitui West East', code: '0003' },
    { name: 'Kitui West West', code: '0004' },
  ],
  'Mwingi Central': [
    { name: 'Mwingi Central Ward', code: '0001' },
    { name: 'Mwingi Town', code: '0002' },
    { name: 'Mwingi Central East', code: '0003' },
    { name: 'Mwingi Central West', code: '0004' },
  ],
  'Mwingi North': [
    { name: 'Mwingi North Ward', code: '0001' },
    { name: 'Mwingi North Central', code: '0002' },
    { name: 'Mwingi North East', code: '0003' },
    { name: 'Mwingi North West', code: '0004' },
  ],
  'Mwingi West': [
    { name: 'Mwingi West Ward', code: '0001' },
    { name: 'Mwingi West Central', code: '0002' },
    { name: 'Mwingi West East', code: '0003' },
    { name: 'Mwingi West West', code: '0004' },
  ],
  // Kwale
  'Kinango': [
    { name: 'Kinango Ward', code: '0001' },
    { name: 'Kinango Central', code: '0002' },
    { name: 'Kinango East', code: '0003' },
    { name: 'Kinango West', code: '0004' },
  ],
  'Lunga Lunga': [
    { name: 'Lunga Lunga Ward', code: '0001' },
    { name: 'Lunga Lunga Central', code: '0002' },
    { name: 'Lunga Lunga East', code: '0003' },
    { name: 'Lunga Lunga West', code: '0004' },
  ],
  'Matuga': [
    { name: 'Matuga Ward', code: '0001' },
    { name: 'Matuga Central', code: '0002' },
    { name: 'Matuga East', code: '0003' },
    { name: 'Matuga West', code: '0004' },
  ],
  'Msambweni': [
    { name: 'Msambweni Ward', code: '0001' },
    { name: 'Msambweni Central', code: '0002' },
    { name: 'Msambweni East', code: '0003' },
    { name: 'Msambweni West', code: '0004' },
  ],
  // Laikipia
  'Laikipia East': [
    { name: 'Laikipia East Ward', code: '0001' },
    { name: 'Laikipia East Central', code: '0002' },
    { name: 'Laikipia East North', code: '0003' },
    { name: 'Laikipia East South', code: '0004' },
  ],
  'Laikipia North': [
    { name: 'Laikipia North Ward', code: '0001' },
    { name: 'Laikipia North Central', code: '0002' },
    { name: 'Laikipia North East', code: '0003' },
    { name: 'Laikipia North West', code: '0004' },
  ],
  'Laikipia West': [
    { name: 'Laikipia West Ward', code: '0001' },
    { name: 'Laikipia West Central', code: '0002' },
    { name: 'Laikipia West East', code: '0003' },
    { name: 'Laikipia West West', code: '0004' },
  ],
  // Lamu
  'Lamu East': [
    { name: 'Lamu East Ward', code: '0001' },
    { name: 'Lamu East Central', code: '0002' },
    { name: 'Lamu East North', code: '0003' },
    { name: 'Lamu East South', code: '0004' },
  ],
  'Lamu West': [
    { name: 'Lamu West Ward', code: '0001' },
    { name: 'Lamu West Central', code: '0002' },
    { name: 'Lamu West East', code: '0003' },
    { name: 'Lamu West West', code: '0004' },
  ],
  // Machakos
  'Kangundo': [
    { name: 'Kangundo Ward', code: '0001' },
    { name: 'Kangundo Central', code: '0002' },
    { name: 'Kangundo East', code: '0003' },
    { name: 'Kangundo West', code: '0004' },
  ],
  'Kathiani': [
    { name: 'Kathiani Ward', code: '0001' },
    { name: 'Kathiani Central', code: '0002' },
    { name: 'Kathiani East', code: '0003' },
    { name: 'Kathiani West', code: '0004' },
  ],
  'Machakos Town': [
    { name: 'Machakos Town Ward', code: '0001' },
    { name: 'Machakos Town Central', code: '0002' },
    { name: 'Machakos Town East', code: '0003' },
    { name: 'Machakos Town West', code: '0004' },
  ],
  'Masinga': [
    { name: 'Masinga Ward', code: '0001' },
    { name: 'Masinga Central', code: '0002' },
    { name: 'Masinga East', code: '0003' },
    { name: 'Masinga West', code: '0004' },
  ],
  'Matungulu': [
    { name: 'Matungulu Ward', code: '0001' },
    { name: 'Matungulu Central', code: '0002' },
    { name: 'Matungulu East', code: '0003' },
    { name: 'Matungulu West', code: '0004' },
  ],
  'Mavoko': [
    { name: 'Mavoko Ward', code: '0001' },
    { name: 'Mavoko Central', code: '0002' },
    { name: 'Mavoko East', code: '0003' },
    { name: 'Mavoko West', code: '0004' },
  ],
  'Mwala': [
    { name: 'Mwala Ward', code: '0001' },
    { name: 'Mwala Central', code: '0002' },
    { name: 'Mwala East', code: '0003' },
    { name: 'Mwala West', code: '0004' },
  ],
  'Yatta': [
    { name: 'Yatta Ward', code: '0001' },
    { name: 'Yatta Central', code: '0002' },
    { name: 'Yatta East', code: '0003' },
    { name: 'Yatta West', code: '0004' },
  ],
  // Makueni
  'Kaiti': [
    { name: 'Kaiti Ward', code: '0001' },
    { name: 'Kaiti Central', code: '0002' },
    { name: 'Kaiti East', code: '0003' },
    { name: 'Kaiti West', code: '0004' },
  ],
  'Kibwezi East': [
    { name: 'Kibwezi East Ward', code: '0001' },
    { name: 'Kibwezi East Central', code: '0002' },
    { name: 'Kibwezi East North', code: '0003' },
    { name: 'Kibwezi East South', code: '0004' },
  ],
  'Kibwezi West': [
    { name: 'Kibwezi West Ward', code: '0001' },
    { name: 'Kibwezi West Central', code: '0002' },
    { name: 'Kibwezi West East', code: '0003' },
    { name: 'Kibwezi West West', code: '0004' },
  ],
  'Kilome': [
    { name: 'Kilome Ward', code: '0001' },
    { name: 'Kilome Central', code: '0002' },
    { name: 'Kilome East', code: '0003' },
    { name: 'Kilome West', code: '0004' },
  ],
  'Makueni': [
    { name: 'Makueni Ward', code: '0001' },
    { name: 'Makueni Central', code: '0002' },
    { name: 'Makueni East', code: '0003' },
    { name: 'Makueni West', code: '0004' },
  ],
  'Mbooni': [
    { name: 'Mbooni Ward', code: '0001' },
    { name: 'Mbooni Central', code: '0002' },
    { name: 'Mbooni East', code: '0003' },
    { name: 'Mbooni West', code: '0004' },
  ],
  // Mandera
  'Banissa': [
    { name: 'Banissa Ward', code: '0001' },
    { name: 'Banissa Central', code: '0002' },
    { name: 'Banissa East', code: '0003' },
    { name: 'Banissa West', code: '0004' },
  ],
  'Lafey': [
    { name: 'Lafey Ward', code: '0001' },
    { name: 'Lafey Central', code: '0002' },
    { name: 'Lafey East', code: '0003' },
    { name: 'Lafey West', code: '0004' },
  ],
  'Mandera East': [
    { name: 'Mandera East Ward', code: '0001' },
    { name: 'Mandera East Central', code: '0002' },
    { name: 'Mandera East North', code: '0003' },
    { name: 'Mandera East South', code: '0004' },
  ],
  'Mandera North': [
    { name: 'Mandera North Ward', code: '0001' },
    { name: 'Mandera North Central', code: '0002' },
    { name: 'Mandera North East', code: '0003' },
    { name: 'Mandera North West', code: '0004' },
  ],
  'Mandera South': [
    { name: 'Mandera South Ward', code: '0001' },
    { name: 'Mandera South Central', code: '0002' },
    { name: 'Mandera South East', code: '0003' },
    { name: 'Mandera South West', code: '0004' },
  ],
  'Mandera West': [
    { name: 'Mandera West Ward', code: '0001' },
    { name: 'Mandera West Central', code: '0002' },
    { name: 'Mandera West East', code: '0003' },
    { name: 'Mandera West West', code: '0004' },
  ],
  // Marsabit
  'Laisamis': [
    { name: 'Laisamis Ward', code: '0001' },
    { name: 'Laisamis Central', code: '0002' },
    { name: 'Laisamis East', code: '0003' },
    { name: 'Laisamis West', code: '0004' },
  ],
  'Moyale': [
    { name: 'Moyale Ward', code: '0001' },
    { name: 'Moyale Central', code: '0002' },
    { name: 'Moyale East', code: '0003' },
    { name: 'Moyale West', code: '0004' },
  ],
  'North Horr': [
    { name: 'North Horr Ward', code: '0001' },
    { name: 'North Horr Central', code: '0002' },
    { name: 'North Horr East', code: '0003' },
    { name: 'North Horr West', code: '0004' },
  ],
  'Saku': [
    { name: 'Saku Ward', code: '0001' },
    { name: 'Saku Central', code: '0002' },
    { name: 'Saku East', code: '0003' },
    { name: 'Saku West', code: '0004' },
  ],
  // Meru
  'Buuri': [
    { name: 'Buuri Ward', code: '0001' },
    { name: 'Buuri Central', code: '0002' },
    { name: 'Buuri East', code: '0003' },
    { name: 'Buuri West', code: '0004' },
  ],
  'Igembe Central': [
    { name: 'Igembe Central Ward', code: '0001' },
    { name: 'Igembe Central East', code: '0002' },
    { name: 'Igembe Central North', code: '0003' },
    { name: 'Igembe Central West', code: '0004' },
  ],
  'Igembe North': [
    { name: 'Igembe North Ward', code: '0001' },
    { name: 'Igembe North Central', code: '0002' },
    { name: 'Igembe North East', code: '0003' },
    { name: 'Igembe North West', code: '0004' },
  ],
  'Igembe South': [
    { name: 'Igembe South Ward', code: '0001' },
    { name: 'Igembe South Central', code: '0002' },
    { name: 'Igembe South East', code: '0003' },
    { name: 'Igembe South West', code: '0004' },
  ],
  'Imenti Central': [
    { name: 'Imenti Central Ward', code: '0001' },
    { name: 'Imenti Central East', code: '0002' },
    { name: 'Imenti Central North', code: '0003' },
    { name: 'Imenti Central West', code: '0004' },
  ],
  'Imenti North': [
    { name: 'Imenti North Ward', code: '0001' },
    { name: 'Imenti North Central', code: '0002' },
    { name: 'Imenti North East', code: '0003' },
    { name: 'Imenti North West', code: '0004' },
  ],
  'Imenti South': [
    { name: 'Imenti South Ward', code: '0001' },
    { name: 'Imenti South Central', code: '0002' },
    { name: 'Imenti South East', code: '0003' },
    { name: 'Imenti South West', code: '0004' },
  ],
  'Tigania East': [
    { name: 'Tigania East Ward', code: '0001' },
    { name: 'Tigania East Central', code: '0002' },
    { name: 'Tigania East North', code: '0003' },
    { name: 'Tigania East South', code: '0004' },
  ],
  'Tigania West': [
    { name: 'Tigania West Ward', code: '0001' },
    { name: 'Tigania West Central', code: '0002' },
    { name: 'Tigania West East', code: '0003' },
    { name: 'Tigania West West', code: '0004' },
  ],
  // Migori
  'Awendo': [
    { name: 'Awendo Ward', code: '0001' },
    { name: 'Awendo Central', code: '0002' },
    { name: 'Awendo East', code: '0003' },
    { name: 'Awendo West', code: '0004' },
  ],
  'Kuria East': [
    { name: 'Kuria East Ward', code: '0001' },
    { name: 'Kuria East Central', code: '0002' },
    { name: 'Kuria East North', code: '0003' },
    { name: 'Kuria East South', code: '0004' },
  ],
  'Kuria West': [
    { name: 'Kuria West Ward', code: '0001' },
    { name: 'Kuria West Central', code: '0002' },
    { name: 'Kuria West East', code: '0003' },
    { name: 'Kuria West West', code: '0004' },
  ],
  'Nyatike': [
    { name: 'Nyatike Ward', code: '0001' },
    { name: 'Nyatike Central', code: '0002' },
    { name: 'Nyatike East', code: '0003' },
    { name: 'Nyatike West', code: '0004' },
  ],
  'Rongo': [
    { name: 'Rongo Ward', code: '0001' },
    { name: 'Rongo Central', code: '0002' },
    { name: 'Rongo East', code: '0003' },
    { name: 'Rongo West', code: '0004' },
  ],
  'Suna East': [
    { name: 'Suna East Ward', code: '0001' },
    { name: 'Suna East Central', code: '0002' },
    { name: 'Suna East North', code: '0003' },
    { name: 'Suna East South', code: '0004' },
  ],
  'Suna West': [
    { name: 'Suna West Ward', code: '0001' },
    { name: 'Suna West Central', code: '0002' },
    { name: 'Suna West East', code: '0003' },
    { name: 'Suna West West', code: '0004' },
  ],
  'Uriri': [
    { name: 'Uriri Ward', code: '0001' },
    { name: 'Uriri Central', code: '0002' },
    { name: 'Uriri East', code: '0003' },
    { name: 'Uriri West', code: '0004' },
  ],
  // Mombasa (keeping existing + expanding)
  'Changamwe': [
    { name: 'Changamwe Ward', code: '0001' },
    { name: 'Junda', code: '0002' },
    { name: 'Kipevu', code: '0003' },
    { name: 'Changamwe Central', code: '0004' },
  ],
  'Jomvu': [
    { name: 'Jomvu Ward', code: '0001' },
    { name: 'Jomvu Central', code: '0002' },
    { name: 'Jomvu East', code: '0003' },
    { name: 'Jomvu West', code: '0004' },
  ],
  'Kisauni': [
    { name: 'Bamburi', code: '0001' },
    { name: 'Chaani', code: '0002' },
    { name: 'Kisauni', code: '0003' },
    { name: 'Mikindani', code: '0004' },
  ],
  'Likoni': [
    { name: 'Likoni Ward', code: '0001' },
    { name: 'Likoni Central', code: '0002' },
    { name: 'Likoni East', code: '0003' },
    { name: 'Likoni West', code: '0004' },
  ],
  'Mvita': [
    { name: 'Mvita Ward', code: '0001' },
    { name: 'Mvita Central', code: '0002' },
    { name: 'Mvita East', code: '0003' },
    { name: 'Mvita West', code: '0004' },
  ],
  'Nyali': [
    { name: 'Nyali Ward', code: '0001' },
    { name: 'Nyali Central', code: '0002' },
    { name: 'Nyali East', code: '0003' },
    { name: 'Nyali West', code: '0004' },
  ],
  // Murang'a
  'Gatanga': [
    { name: 'Gatanga Ward', code: '0001' },
    { name: 'Gatanga Central', code: '0002' },
    { name: 'Gatanga East', code: '0003' },
    { name: 'Gatanga West', code: '0004' },
  ],
  'Kahuro': [
    { name: 'Kahuro Ward', code: '0001' },
    { name: 'Kahuro Central', code: '0002' },
    { name: 'Kahuro East', code: '0003' },
    { name: 'Kahuro West', code: '0004' },
  ],
  'Kandara': [
    { name: 'Kandara Ward', code: '0001' },
    { name: 'Kandara Central', code: '0002' },
    { name: 'Kandara East', code: '0003' },
    { name: 'Kandara West', code: '0004' },
  ],
  'Kangema': [
    { name: 'Kangema Ward', code: '0001' },
    { name: 'Kangema Central', code: '0002' },
    { name: 'Kangema East', code: '0003' },
    { name: 'Kangema West', code: '0004' },
  ],
  'Kigumo': [
    { name: 'Kigumo Ward', code: '0001' },
    { name: 'Kigumo Central', code: '0002' },
    { name: 'Kigumo East', code: '0003' },
    { name: 'Kigumo West', code: '0004' },
  ],
  'Kiharu': [
    { name: 'Kiharu Ward', code: '0001' },
    { name: 'Kiharu Central', code: '0002' },
    { name: 'Kiharu East', code: '0003' },
    { name: 'Kiharu West', code: '0004' },
  ],
  'Mathioya': [
    { name: 'Mathioya Ward', code: '0001' },
    { name: 'Mathioya Central', code: '0002' },
    { name: 'Mathioya East', code: '0003' },
    { name: 'Mathioya West', code: '0004' },
  ],
  'Maragwa': [
    { name: 'Maragwa Ward', code: '0001' },
    { name: 'Maragwa Central', code: '0002' },
    { name: 'Maragwa East', code: '0003' },
    { name: 'Maragwa West', code: '0004' },
  ],
  // Nairobi
  'Dagoretti North': [
    { name: 'Dagoretti North Ward', code: '0001' },
    { name: 'Dagoretti North Central', code: '0002' },
    { name: 'Dagoretti North East', code: '0003' },
    { name: 'Dagoretti North West', code: '0004' },
  ],
  'Dagoretti South': [
    { name: 'Dagoretti South Ward', code: '0001' },
    { name: 'Dagoretti South Central', code: '0002' },
    { name: 'Dagoretti South East', code: '0003' },
    { name: 'Dagoretti South West', code: '0004' },
  ],
  'Embakasi Central': [
    { name: 'Embakasi Central Ward', code: '0001' },
    { name: 'Embakasi Central Central', code: '0002' },
    { name: 'Embakasi Central East', code: '0003' },
    { name: 'Embakasi Central West', code: '0004' },
  ],
  'Embakasi East': [
    { name: 'Embakasi East Ward', code: '0001' },
    { name: 'Embakasi East Central', code: '0002' },
    { name: 'Embakasi East North', code: '0003' },
    { name: 'Embakasi East South', code: '0004' },
  ],
  'Embakasi North': [
    { name: 'Embakasi North Ward', code: '0001' },
    { name: 'Embakasi North Central', code: '0002' },
    { name: 'Embakasi North East', code: '0003' },
    { name: 'Embakasi North West', code: '0004' },
  ],
  'Embakasi South': [
    { name: 'Embakasi South Ward', code: '0001' },
    { name: 'Embakasi South Central', code: '0002' },
    { name: 'Embakasi South East', code: '0003' },
    { name: 'Embakasi South West', code: '0004' },
  ],
  'Embakasi West': [
    { name: 'Embakasi West Ward', code: '0001' },
    { name: 'Embakasi West Central', code: '0002' },
    { name: 'Embakasi West East', code: '0003' },
    { name: 'Embakasi West West', code: '0004' },
  ],
  'Kamukunji': [
    { name: 'Eastleigh North', code: '0001' },
    { name: 'Eastleigh South', code: '0002' },
    { name: 'Kamukunji', code: '0003' },
    { name: 'Pumwani', code: '0004' },
  ],
  'Kasarani': [
    { name: 'Dandora', code: '0001' },
    { name: 'Embakasi', code: '0002' },
    { name: 'Kasarani', code: '0003' },
    { name: 'Ruai', code: '0004' },
    { name: 'Woodley', code: '0005' },
  ],
  'Kibra': [
    { name: 'Kibra Ward', code: '0001' },
    { name: 'Kibra Central', code: '0002' },
    { name: 'Kibra East', code: '0003' },
    { name: 'Kibra West', code: '0004' },
  ],
  'Lang\'ata': [
    { name: 'Lang\'ata Ward', code: '0001' },
    { name: 'Lang\'ata Central', code: '0002' },
    { name: 'Lang\'ata East', code: '0003' },
    { name: 'Lang\'ata West', code: '0004' },
  ],
  'Makadara': [
    { name: 'Makadara Ward', code: '0001' },
    { name: 'Makadara Central', code: '0002' },
    { name: 'Makadara East', code: '0003' },
    { name: 'Makadara West', code: '0004' },
  ],
  'Mathare': [
    { name: 'Mathare Ward', code: '0001' },
    { name: 'Mathare Central', code: '0002' },
    { name: 'Mathare East', code: '0003' },
    { name: 'Mathare West', code: '0004' },
  ],
  'Roysambu': [
    { name: 'Roysambu Ward', code: '0001' },
    { name: 'Roysambu Central', code: '0002' },
    { name: 'Roysambu East', code: '0003' },
    { name: 'Roysambu West', code: '0004' },
  ],
  'Ruaraka': [
    { name: 'Ruaraka Ward', code: '0001' },
    { name: 'Ruaraka Central', code: '0002' },
    { name: 'Ruaraka East', code: '0003' },
    { name: 'Ruaraka West', code: '0004' },
  ],
  'Starehe': [
    { name: 'Starehe Ward', code: '0001' },
    { name: 'Starehe Central', code: '0002' },
    { name: 'Starehe East', code: '0003' },
    { name: 'Starehe West', code: '0004' },
  ],
  'Westlands': [
    { name: 'Westlands Ward', code: '0001' },
    { name: 'Westlands Central', code: '0002' },
    { name: 'Westlands East', code: '0003' },
    { name: 'Westlands West', code: '0004' },
  ],
  // Nakuru (keeping existing + expanding)
  'Bahati': [
    { name: 'Bahati', code: '0001' },
    { name: 'Favours', code: '0002' },
    { name: 'Kiamwathi', code: '0003' },
    { name: 'Shauri Moyo', code: '0004' },
  ],
  'Gilgil': [
    { name: 'Gilgil Ward', code: '0001' },
    { name: 'Gilgil Central', code: '0002' },
    { name: 'Gilgil East', code: '0003' },
    { name: 'Gilgil West', code: '0004' },
  ],
  'Kuresoi North': [
    { name: 'Kuresoi North Ward', code: '0001' },
    { name: 'Kuresoi North Central', code: '0002' },
    { name: 'Kuresoi North East', code: '0003' },
    { name: 'Kuresoi North West', code: '0004' },
  ],
  'Kuresoi South': [
    { name: 'Kuresoi South Ward', code: '0001' },
    { name: 'Kuresoi South Central', code: '0002' },
    { name: 'Kuresoi South East', code: '0003' },
    { name: 'Kuresoi South West', code: '0004' },
  ],
  'Molo': [
    { name: 'Molo Ward', code: '0001' },
    { name: 'Molo Central', code: '0002' },
    { name: 'Molo East', code: '0003' },
    { name: 'Molo West', code: '0004' },
  ],
  'Nakuru Town': [
    { name: 'Nakuru Town Ward', code: '0001' },
    { name: 'Nakuru Town Central', code: '0002' },
    { name: 'Nakuru Town East', code: '0003' },
    { name: 'Nakuru Town West', code: '0004' },
  ],
  'Naivasha': [
    { name: 'Naivasha Ward', code: '0001' },
    { name: 'Naivasha Central', code: '0002' },
    { name: 'Naivasha East', code: '0003' },
    { name: 'Naivasha West', code: '0004' },
  ],
  'Njoro': [
    { name: 'Njoro Ward', code: '0001' },
    { name: 'Njoro Central', code: '0002' },
    { name: 'Njoro East', code: '0003' },
    { name: 'Njoro West', code: '0004' },
  ],
  'Rongai': [
    { name: 'Rongai Ward', code: '0001' },
    { name: 'Rongai Central', code: '0002' },
    { name: 'Rongai East', code: '0003' },
    { name: 'Rongai West', code: '0004' },
  ],
  'Subukia': [
    { name: 'Subukia Ward', code: '0001' },
    { name: 'Subukia Central', code: '0002' },
    { name: 'Subukia East', code: '0003' },
    { name: 'Subukia West', code: '0004' },
  ],
  // Nandi
  'Aldai': [
    { name: 'Aldai Ward', code: '0001' },
    { name: 'Aldai Central', code: '0002' },
    { name: 'Aldai East', code: '0003' },
    { name: 'Aldai West', code: '0004' },
  ],
  'Chesumei': [
    { name: 'Chesumei Ward', code: '0001' },
    { name: 'Chesumei Central', code: '0002' },
    { name: 'Chesumei East', code: '0003' },
    { name: 'Chesumei West', code: '0004' },
  ],
  'Emgwen': [
    { name: 'Emgwen Ward', code: '0001' },
    { name: 'Emgwen Central', code: '0002' },
    { name: 'Emgwen East', code: '0003' },
    { name: 'Emgwen West', code: '0004' },
  ],
  'Mosop': [
    { name: 'Mosop Ward', code: '0001' },
    { name: 'Mosop Central', code: '0002' },
    { name: 'Mosop East', code: '0003' },
    { name: 'Mosop West', code: '0004' },
  ],
  'Nandi Hills': [
    { name: 'Nandi Hills Ward', code: '0001' },
    { name: 'Nandi Hills Central', code: '0002' },
    { name: 'Nandi Hills East', code: '0003' },
    { name: 'Nandi Hills West', code: '0004' },
  ],
  'Tinderet': [
    { name: 'Tinderet Ward', code: '0001' },
    { name: 'Tinderet Central', code: '0002' },
    { name: 'Tinderet East', code: '0003' },
    { name: 'Tinderet West', code: '0004' },
  ],
  // Narok
  'Narok East': [
    { name: 'Narok East Ward', code: '0001' },
    { name: 'Narok East Central', code: '0002' },
    { name: 'Narok East North', code: '0003' },
    { name: 'Narok East South', code: '0004' },
  ],
  'Narok North': [
    { name: 'Narok North Ward', code: '0001' },
    { name: 'Narok North Central', code: '0002' },
    { name: 'Narok North East', code: '0003' },
    { name: 'Narok North West', code: '0004' },
  ],
  'Narok South': [
    { name: 'Narok South Ward', code: '0001' },
    { name: 'Narok South Central', code: '0002' },
    { name: 'Narok South East', code: '0003' },
    { name: 'Narok South West', code: '0004' },
  ],
  'Narok West': [
    { name: 'Narok West Ward', code: '0001' },
    { name: 'Narok West Central', code: '0002' },
    { name: 'Narok West East', code: '0003' },
    { name: 'Narok West West', code: '0004' },
  ],
  'Transmara East': [
    { name: 'Transmara East Ward', code: '0001' },
    { name: 'Transmara East Central', code: '0002' },
    { name: 'Transmara East North', code: '0003' },
    { name: 'Transmara East South', code: '0004' },
  ],
  'Transmara West': [
    { name: 'Transmara West Ward', code: '0001' },
    { name: 'Transmara West Central', code: '0002' },
    { name: 'Transmara West East', code: '0003' },
    { name: 'Transmara West West', code: '0004' },
  ],
  // Nyamira
  'Borabu': [
    { name: 'Borabu Ward', code: '0001' },
    { name: 'Borabu Central', code: '0002' },
    { name: 'Borabu East', code: '0003' },
    { name: 'Borabu West', code: '0004' },
  ],
  'Kitutu Masaba': [
    { name: 'Kitutu Masaba Ward', code: '0001' },
    { name: 'Kitutu Masaba Central', code: '0002' },
    { name: 'Kitutu Masaba East', code: '0003' },
    { name: 'Kitutu Masaba West', code: '0004' },
  ],
  'North Mugirango': [
    { name: 'North Mugirango Ward', code: '0001' },
    { name: 'North Mugirango Central', code: '0002' },
    { name: 'North Mugirango East', code: '0003' },
    { name: 'North Mugirango West', code: '0004' },
  ],
  'West Mugirango': [
    { name: 'West Mugirango Ward', code: '0001' },
    { name: 'West Mugirango Central', code: '0002' },
    { name: 'West Mugirango East', code: '0003' },
    { name: 'West Mugirango West', code: '0004' },
  ],
  // Nyeri
  'Kieni': [
    { name: 'Kieni Ward', code: '0001' },
    { name: 'Kieni Central', code: '0002' },
    { name: 'Kieni East', code: '0003' },
    { name: 'Kieni West', code: '0004' },
  ],
  'Mathira': [
    { name: 'Mathira Ward', code: '0001' },
    { name: 'Mathira Central', code: '0002' },
    { name: 'Mathira East', code: '0003' },
    { name: 'Mathira West', code: '0004' },
  ],
  'Mukurweini': [
    { name: 'Mukurweini Ward', code: '0001' },
    { name: 'Mukurweini Central', code: '0002' },
    { name: 'Mukurweini East', code: '0003' },
    { name: 'Mukurweini West', code: '0004' },
  ],
  'Nyeri Town': [
    { name: 'Nyeri Town Ward', code: '0001' },
    { name: 'Nyeri Town Central', code: '0002' },
    { name: 'Nyeri Town East', code: '0003' },
    { name: 'Nyeri Town West', code: '0004' },
  ],
  'Othaya': [
    { name: 'Othaya Ward', code: '0001' },
    { name: 'Othaya Central', code: '0002' },
    { name: 'Othaya East', code: '0003' },
    { name: 'Othaya West', code: '0004' },
  ],
  'Tetu': [
    { name: 'Tetu Ward', code: '0001' },
    { name: 'Tetu Central', code: '0002' },
    { name: 'Tetu East', code: '0003' },
    { name: 'Tetu West', code: '0004' },
  ],
  // Samburu
  'Samburu East': [
    { name: 'Samburu East Ward', code: '0001' },
    { name: 'Samburu East Central', code: '0002' },
    { name: 'Samburu East North', code: '0003' },
    { name: 'Samburu East South', code: '0004' },
  ],
  'Samburu North': [
    { name: 'Samburu North Ward', code: '0001' },
    { name: 'Samburu North Central', code: '0002' },
    { name: 'Samburu North East', code: '0003' },
    { name: 'Samburu North West', code: '0004' },
  ],
  'Samburu West': [
    { name: 'Samburu West Ward', code: '0001' },
    { name: 'Samburu West Central', code: '0002' },
    { name: 'Samburu West East', code: '0003' },
    { name: 'Samburu West West', code: '0004' },
  ],
  // Siaya - Alego Usonga already defined above for Kisumu
  'Bondo': [
    { name: 'Bondo Ward', code: '0001' },
    { name: 'Bondo Central', code: '0002' },
    { name: 'Bondo East', code: '0003' },
    { name: 'Bondo West', code: '0004' },
  ],
  'Gem': [
    { name: 'Gem Ward', code: '0001' },
    { name: 'Gem Central', code: '0002' },
    { name: 'Gem East', code: '0003' },
    { name: 'Gem West', code: '0004' },
  ],
  'Rarieda': [
    { name: 'Rarieda Ward', code: '0001' },
    { name: 'Rarieda Central', code: '0002' },
    { name: 'Rarieda East', code: '0003' },
    { name: 'Rarieda West', code: '0004' },
  ],
  'Ugenya': [
    { name: 'Ugenya Ward', code: '0001' },
    { name: 'Ugenya Central', code: '0002' },
    { name: 'Ugenya East', code: '0003' },
    { name: 'Ugenya West', code: '0004' },
  ],
  'Ugunja': [
    { name: 'Ugunja Ward', code: '0001' },
    { name: 'Ugunja Central', code: '0002' },
    { name: 'Ugunja East', code: '0003' },
    { name: 'Ugunja West', code: '0004' },
  ],
  // Taita-Taveta
  'Mwatate': [
    { name: 'Mwatate Ward', code: '0001' },
    { name: 'Mwatate Central', code: '0002' },
    { name: 'Mwatate East', code: '0003' },
    { name: 'Mwatate West', code: '0004' },
  ],
  'Taveta': [
    { name: 'Taveta Ward', code: '0001' },
    { name: 'Taveta Central', code: '0002' },
    { name: 'Taveta East', code: '0003' },
    { name: 'Taveta West', code: '0004' },
  ],
  'Voi': [
    { name: 'Voi Ward', code: '0001' },
    { name: 'Voi Central', code: '0002' },
    { name: 'Voi East', code: '0003' },
    { name: 'Voi West', code: '0004' },
  ],
  'Wundanyi': [
    { name: 'Wundanyi Ward', code: '0001' },
    { name: 'Wundanyi Central', code: '0002' },
    { name: 'Wundanyi East', code: '0003' },
    { name: 'Wundanyi West', code: '0004' },
  ],
  // Tana River
  'Bura': [
    { name: 'Bura Ward', code: '0001' },
    { name: 'Bura Central', code: '0002' },
    { name: 'Bura East', code: '0003' },
    { name: 'Bura West', code: '0004' },
  ],
  'Galole': [
    { name: 'Galole Ward', code: '0001' },
    { name: 'Galole Central', code: '0002' },
    { name: 'Galole East', code: '0003' },
    { name: 'Galole West', code: '0004' },
  ],
  'Garsen': [
    { name: 'Garsen Ward', code: '0001' },
    { name: 'Garsen Central', code: '0002' },
    { name: 'Garsen East', code: '0003' },
    { name: 'Garsen West', code: '0004' },
  ],
  // Transnzoia
  'Cherangany': [
    { name: 'Cherangany Ward', code: '0001' },
    { name: 'Cherangany Central', code: '0002' },
    { name: 'Cherangany East', code: '0003' },
    { name: 'Cherangany West', code: '0004' },
  ],
  'Endebess': [
    { name: 'Endebess Ward', code: '0001' },
    { name: 'Endebess Central', code: '0002' },
    { name: 'Endebess East', code: '0003' },
    { name: 'Endebess West', code: '0004' },
  ],
  'Kiminini': [
    { name: 'Kiminini Ward', code: '0001' },
    { name: 'Kiminini Central', code: '0002' },
    { name: 'Kiminini East', code: '0003' },
    { name: 'Kiminini West', code: '0004' },
  ],
  'Kwanza': [
    { name: 'Kwanza Ward', code: '0001' },
    { name: 'Kwanza Central', code: '0002' },
    { name: 'Kwanza East', code: '0003' },
    { name: 'Kwanza West', code: '0004' },
  ],
  'Saboti': [
    { name: 'Saboti Ward', code: '0001' },
    { name: 'Saboti Central', code: '0002' },
    { name: 'Saboti East', code: '0003' },
    { name: 'Saboti West', code: '0004' },
  ],
  // Turkana
  'Loima': [
    { name: 'Loima Ward', code: '0001' },
    { name: 'Loima Central', code: '0002' },
    { name: 'Loima East', code: '0003' },
    { name: 'Loima West', code: '0004' },
  ],
  'Turkana Central': [
    { name: 'Turkana Central Ward', code: '0001' },
    { name: 'Turkana Central East', code: '0002' },
    { name: 'Turkana Central North', code: '0003' },
    { name: 'Turkana Central West', code: '0004' },
  ],
  'Turkana East': [
    { name: 'Turkana East Ward', code: '0001' },
    { name: 'Turkana East Central', code: '0002' },
    { name: 'Turkana East North', code: '0003' },
    { name: 'Turkana East South', code: '0004' },
  ],
  'Turkana North': [
    { name: 'Turkana North Ward', code: '0001' },
    { name: 'Turkana North Central', code: '0002' },
    { name: 'Turkana North East', code: '0003' },
    { name: 'Turkana North West', code: '0004' },
  ],
  'Turkana South': [
    { name: 'Turkana South Ward', code: '0001' },
    { name: 'Turkana South Central', code: '0002' },
    { name: 'Turkana South East', code: '0003' },
    { name: 'Turkana South West', code: '0004' },
  ],
  'Turkana West': [
    { name: 'Turkana West Ward', code: '0001' },
    { name: 'Turkana West Central', code: '0002' },
    { name: 'Turkana West East', code: '0003' },
    { name: 'Turkana West West', code: '0004' },
  ],
  // Tharaka-Nithi
  'Chuka Igambang\'ombe': [
    { name: 'Chuka Ward', code: '0001' },
    { name: 'Igambang\'ombe Ward', code: '0002' },
    { name: 'Chuka Central', code: '0003' },
    { name: 'Chuka East', code: '0004' },
  ],
  'Maara': [
    { name: 'Maara Ward', code: '0001' },
    { name: 'Maara Central', code: '0002' },
    { name: 'Maara East', code: '0003' },
    { name: 'Maara West', code: '0004' },
  ],
  'Tharaka': [
    { name: 'Tharaka Ward', code: '0001' },
    { name: 'Tharaka Central', code: '0002' },
    { name: 'Tharaka East', code: '0003' },
    { name: 'Tharaka West', code: '0004' },
  ],
  // Uasin Gishu
  'Ainabkoi': [
    { name: 'Ainabkoi Ward', code: '0001' },
    { name: 'Ainabkoi Central', code: '0002' },
    { name: 'Ainabkoi East', code: '0003' },
    { name: 'Ainabkoi West', code: '0004' },
  ],
  'Kapseret': [
    { name: 'Kapseret Ward', code: '0001' },
    { name: 'Kapseret Central', code: '0002' },
    { name: 'Kapseret East', code: '0003' },
    { name: 'Kapseret West', code: '0004' },
  ],
  'Kesses': [
    { name: 'Kesses Ward', code: '0001' },
    { name: 'Kesses Central', code: '0002' },
    { name: 'Kesses East', code: '0003' },
    { name: 'Kesses West', code: '0004' },
  ],
  'Moiben': [
    { name: 'Moiben Ward', code: '0001' },
    { name: 'Moiben Central', code: '0002' },
    { name: 'Moiben East', code: '0003' },
    { name: 'Moiben West', code: '0004' },
  ],
  'Soy': [
    { name: 'Soy Ward', code: '0001' },
    { name: 'Soy Central', code: '0002' },
    { name: 'Soy East', code: '0003' },
    { name: 'Soy West', code: '0004' },
  ],
  'Turbo': [
    { name: 'Turbo Ward', code: '0001' },
    { name: 'Turbo Central', code: '0002' },
    { name: 'Turbo East', code: '0003' },
    { name: 'Turbo West', code: '0004' },
  ],
  // Vihiga
  'Emuhaya': [
    { name: 'Emuhaya Ward', code: '0001' },
    { name: 'Emuhaya Central', code: '0002' },
    { name: 'Emuhaya East', code: '0003' },
    { name: 'Emuhaya West', code: '0004' },
  ],
  'Hamisi': [
    { name: 'Hamisi Ward', code: '0001' },
    { name: 'Hamisi Central', code: '0002' },
    { name: 'Hamisi East', code: '0003' },
    { name: 'Hamisi West', code: '0004' },
  ],
  'Luanda': [
    { name: 'Luanda Ward', code: '0001' },
    { name: 'Luanda Central', code: '0002' },
    { name: 'Luanda East', code: '0003' },
    { name: 'Luanda West', code: '0004' },
  ],
  'Sabatia': [
    { name: 'Sabatia Ward', code: '0001' },
    { name: 'Sabatia Central', code: '0002' },
    { name: 'Sabatia East', code: '0003' },
    { name: 'Sabatia West', code: '0004' },
  ],
  'Vihiga': [
    { name: 'Vihiga Ward', code: '0001' },
    { name: 'Vihiga Central', code: '0002' },
    { name: 'Vihiga East', code: '0003' },
    { name: 'Vihiga West', code: '0004' },
  ],
  // Wajir
  'Eldas': [
    { name: 'Eldas Ward', code: '0001' },
    { name: 'Eldas Central', code: '0002' },
    { name: 'Eldas East', code: '0003' },
    { name: 'Eldas West', code: '0004' },
  ],
  'Tarbaj': [
    { name: 'Tarbaj Ward', code: '0001' },
    { name: 'Tarbaj Central', code: '0002' },
    { name: 'Tarbaj East', code: '0003' },
    { name: 'Tarbaj West', code: '0004' },
  ],
  'Wajir East': [
    { name: 'Wajir East Ward', code: '0001' },
    { name: 'Wajir East Central', code: '0002' },
    { name: 'Wajir East North', code: '0003' },
    { name: 'Wajir East South', code: '0004' },
  ],
  'Wajir North': [
    { name: 'Wajir North Ward', code: '0001' },
    { name: 'Wajir North Central', code: '0002' },
    { name: 'Wajir North East', code: '0003' },
    { name: 'Wajir North West', code: '0004' },
  ],
  'Wajir South': [
    { name: 'Wajir South Ward', code: '0001' },
    { name: 'Wajir South Central', code: '0002' },
    { name: 'Wajir South East', code: '0003' },
    { name: 'Wajir South West', code: '0004' },
  ],
  'Wajir West': [
    { name: 'Wajir West Ward', code: '0001' },
    { name: 'Wajir West Central', code: '0002' },
    { name: 'Wajir West East', code: '0003' },
    { name: 'Wajir West West', code: '0004' },
  ],
  // West Pokot
  'Kapenguria': [
    { name: 'Kapenguria Ward', code: '0001' },
    { name: 'Kapenguria Central', code: '0002' },
    { name: 'Kapenguria East', code: '0003' },
    { name: 'Kapenguria West', code: '0004' },
  ],
  'Kacheliba': [
    { name: 'Kacheliba Ward', code: '0001' },
    { name: 'Kacheliba Central', code: '0002' },
    { name: 'Kacheliba East', code: '0003' },
    { name: 'Kacheliba West', code: '0004' },
  ],
  'Pokot South': [
    { name: 'Pokot South Ward', code: '0001' },
    { name: 'Pokot South Central', code: '0002' },
    { name: 'Pokot South East', code: '0003' },
    { name: 'Pokot South West', code: '0004' },
  ],
  'Sigor': [
    { name: 'Sigor Ward', code: '0001' },
    { name: 'Sigor Central', code: '0002' },
    { name: 'Sigor East', code: '0003' },
    { name: 'Sigor West', code: '0004' },
  ],
};

export function registerLocationsRoutes(app: App) {
  // Get all counties
  app.fastify.get(
    '/api/locations/counties',
    {
      schema: {
        description: 'Get all Kenyan counties',
        tags: ['locations'],
      },
    },
    async (request: FastifyRequest, reply: FastifyReply) => {
      app.logger.info('Fetching all counties');
      return kenyaCounties;
    }
  );

  // Get constituencies for a county
  app.fastify.get<{ Params: { county: string } }>(
    '/api/locations/constituencies/:county',
    {
      schema: {
        description: 'Get constituencies for a county',
        tags: ['locations'],
        params: {
          type: 'object',
          properties: {
            county: { type: 'string' },
          },
          required: ['county'],
        },
      },
    },
    async (request: FastifyRequest, reply: FastifyReply) => {
      const { county } = request.params as { county: string };
      app.logger.info({ county }, 'Fetching constituencies');

      const constituencies = constituenciesByCounty[county] || [];
      return constituencies.map((c) => ({
        name: c.name,
        code: c.code,
        county,
      }));
    }
  );

  // Get wards for a constituency
  app.fastify.get<{ Params: { constituency: string } }>(
    '/api/locations/wards/:constituency',
    {
      schema: {
        description: 'Get wards for a constituency',
        tags: ['locations'],
        params: {
          type: 'object',
          properties: {
            constituency: { type: 'string' },
          },
          required: ['constituency'],
        },
      },
    },
    async (request: FastifyRequest, reply: FastifyReply) => {
      const { constituency } = request.params as { constituency: string };
      app.logger.info({ constituency }, 'Fetching wards');

      const wards = wardsByConstituency[constituency] || [];
      return wards.map((w) => ({
        name: w.name,
        code: w.code,
        constituency,
      }));
    }
  );
}
